# Generated by Django 6.0.2 on 2026-03-09 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_options_job_experience_level_job_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Manufacturing', 'Manufacturing'), ('Security', 'Security'), ('Retail', 'Retail'), ('Education', 'Education'), ('Construction', 'Construction'), ('Transportation', 'Transportation'), ('Hospitality', 'Hospitality'), ('Media', 'Media'), ('Consulting', 'Consulting'), ('Legal', 'Legal'), ('Real Estate', 'Real Estate'), ('Energy', 'Energy'), ('Telecommunications', 'Telecommunications'), ('Government', 'Government'), ('Non-Profit', 'Non-Profit'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['industry'], name='jobs_job_industr_a3aeef_idx'),
        ),
    ]
