# Generated by Django 6.0.2 on 2026-04-23 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_requirements_job_skills_alter_job_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Trainee', 'Trainee'), ('Entry', 'Entry Level'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Executive', 'Executive')], default='Mid-Level', max_length=50),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_archived'], name='jobs_job_is_arch_26ac54_idx'),
        ),
    ]
