# Generated by Django 6.0.2 on 2026-04-26 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_add_job_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the job has been approved for public viewing'),
        ),
        migrations.AddField(
            model_name='job',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the job was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who reviewed this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_approved', 'approval_status'], name='jobs_job_is_appr_360365_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-reviewed_at'], name='jobs_job_reviewe_4c0fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_by', 'is_approved'], name='jobs_job_created_08dabd_idx'),
        ),
    ]
