# Generated by Django 6.0.2 on 2026-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Insight Comment', 'verbose_name_plural': 'Insight Comments'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Insight', 'verbose_name_plural': 'Insights'},
        ),
        migrations.AlterModelOptions(
            name='blogsubscriber',
            options={'ordering': ['-subscribed_date'], 'verbose_name': 'Insight Subscriber', 'verbose_name_plural': 'Insight Subscribers'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_display_picture',
            field=models.URLField(blank=True, help_text="URL to the author's display picture/avatar"),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional external link (for linking to external articles)'),
        ),
    ]
