# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        # Add new fields to SubscriptionPlan
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_profiles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_ai_pastes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        # Add new fields to Subscription
        migrations.AddField(
            model_name='subscription',
            name='ai_pastes_used_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_usage_reset',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
