# Generated by Django 6.0.2 on 2026-03-13 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_2fa_enabled_twofactortoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_target', models.PositiveIntegerField(default=10, help_text='Number of applications to submit per week')),
                ('applications_this_week', models.PositiveIntegerField(default=0)),
                ('week_start_date', models.DateField(help_text='Start date of the current week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_search_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
