# Generated by Django 6.0.2 on 2026-03-13 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_jobsearchgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.CharField(help_text='Custom URL slug for sharing', max_length=50, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether profile is publicly visible')),
                ('show_applications_count', models.BooleanField(default=True, help_text='Show total applications count')),
                ('show_interviews_count', models.BooleanField(default=True, help_text='Show interviews count')),
                ('show_offers_count', models.BooleanField(default=True, help_text='Show offers count')),
                ('show_success_rate', models.BooleanField(default=True, help_text='Show success rate')),
                ('display_name', models.CharField(blank=True, help_text='Custom display name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
