# Generated by Django 6.0.2 on 2026-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_publicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_data_collection',
            field=models.BooleanField(default=True, help_text='Allow analytics data collection'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_summary',
            field=models.BooleanField(default=True, help_text='Receive weekly summary emails'),
        ),
    ]
