# Generated by Django 6.0.2 on 2026-04-26 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_approval_status_job_is_approved_and_more'),
        ('users', '0007_user_allow_data_collection_user_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_to_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member this user is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_job_limit',
            field=models.PositiveIntegerField(default=5, help_text='Maximum jobs that can be posted per day'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_poster',
            field=models.BooleanField(default=False, help_text='Whether user can post jobs (requires approval)'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_job_limit',
            field=models.PositiveIntegerField(default=50, help_text='Maximum jobs that can be posted per month'),
        ),
        migrations.CreateModel(
            name='JobPosterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs_posted', models.PositiveIntegerField(default=0)),
                ('total_jobs_approved', models.PositiveIntegerField(default=0)),
                ('total_jobs_rejected', models.PositiveIntegerField(default=0)),
                ('total_jobs_pending', models.PositiveIntegerField(default=0)),
                ('average_approval_time', models.DurationField(blank=True, help_text='Average time from posting to approval', null=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_applications_received', models.PositiveIntegerField(default=0)),
                ('average_applications_per_job', models.FloatField(default=0.0)),
                ('last_post_date', models.DateField(blank=True, null=True)),
                ('jobs_posted_today', models.PositiveIntegerField(default=0)),
                ('current_month', models.DateField(blank=True, help_text='Current month for tracking (YYYY-MM-01)', null=True)),
                ('jobs_posted_this_month', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Poster Statistics',
                'verbose_name_plural': 'Job Poster Statistics',
            },
        ),
        migrations.CreateModel(
            name='JobReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Review comment')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note (not visible to job poster)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='jobs.job')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Review Comment',
                'verbose_name_plural': 'Job Review Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is active')),
                ('staff', models.ForeignKey(help_text='Staff member (job reviewer/approver)', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User assigned to this staff member', on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Assignment',
                'verbose_name_plural': 'Staff Assignments',
            },
        ),
        migrations.DeleteModel(
            name='JobSearchGoal',
        ),
        migrations.AddIndex(
            model_name='jobposterstats',
            index=models.Index(fields=['user', 'current_month'], name='users_jobpo_user_id_b55d34_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposterstats',
            index=models.Index(fields=['last_post_date'], name='users_jobpo_last_po_2255f0_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['staff', 'is_active'], name='users_staff_staff_i_e0c07a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['user', 'is_active'], name='users_staff_user_id_2e6674_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffassignment',
            unique_together={('staff', 'user')},
        ),
    ]
