# Generated by Django 6.0.2 on 2026-05-12 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_assigned_to_staff_user_daily_job_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactortoken',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='jobposterstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twofactortoken',
            name='token',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
