# Generated by Django 6.0.2 on 2026-03-08 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], db_index=True, default='saved', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='application_user_id_55b4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', '-created_at'], name='application_user_id_aaf56b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='application_status_db7a61_idx'),
        ),
    ]
