# Generated by Django 6.0.2 on 2026-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, help_text='Job description from the listing'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_questions',
            field=models.TextField(blank=True, help_text='Questions from the recruiter'),
        ),
        migrations.AddField(
            model_name='application',
            name='requirements',
            field=models.TextField(blank=True, help_text='Job requirements and qualifications'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.URLField(blank=True, help_text='Resume URL (uploaded and compressed)', max_length=500),
        ),
    ]
