# Generated by Django 6.0.2 on 2026-03-09 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_archived_application_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'deleted_at'], name='application_user_id_5802cc_idx'),
        ),
    ]
