# Generated by Django 6.0.2 on 2026-03-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Date to follow up', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='follow_up_sent',
            field=models.BooleanField(default=False, help_text='Whether follow-up reminder was sent'),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('company_website', 'Company Website'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('other', 'Other')], help_text='Where the application came from', max_length=50),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('technical', 'Technical'), ('hr', 'HR'), ('panel', 'Panel'), ('final', 'Final'), ('other', 'Other')], default='phone', max_length=20)),
                ('interviewer', models.CharField(blank=True, help_text='Interviewer name(s)', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Location or meeting link', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'ordering': ['-interview_date', '-created_at'],
            },
        ),
    ]
