# Generated by Django 6.0.2 on 2026-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('jobberman', 'Jobberman'), ('glassdoor', 'Glassdoor'), ('company_website', 'Company Website'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('other', 'Other')], help_text='Where the application came from', max_length=50),
        ),
    ]
