# Generated by Django 6.0.2 on 2026-03-12 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0006_application_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('interview_questions', models.JSONField(default=list, help_text='List of interview questions with categories')),
                ('skill_assessments', models.JSONField(default=dict, help_text='Skill assessments and gaps analysis')),
                ('recommendations', models.JSONField(default=list, help_text='Personalized recommendations based on profile')),
                ('company_insights', models.JSONField(default=dict, help_text='Information about the company')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prep_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Preparation',
                'verbose_name_plural': 'Interview Preparations',
                'ordering': ['-created_at'],
            },
        ),
    ]
